package com.agent.agentApi.model.schema;

import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.json.JsonMapper;


public record OutputChatSchema(
    List<Message> messages
) {

  public record Message(
      String content
  ) {}

  public static String toJSONSchema() {
    JsonMapper mapper = new JsonMapper();
    try {
      return mapper.writeValueAsString(
        Map.of(
          "type", "OBJECT",
          "properties", Map.of(

              "messages", Map.of(
                  "type", "ARRAY",
                  "nullable", false,
                  "description", "List of messages generated by the agent",
                  "items", Map.of(
                      "type", "OBJECT",
                      "properties", Map.of(
                          "content", Map.of(
                              "type", "STRING",
                              "nullable", true,
                              "description", "The message content"
                          )
                      ),
                      "required", List.of("content")
                  )
              )
          )
      )
      );
    } catch (JsonProcessingException e) {

      System.err.print("Falha em serializar o schema de saída do Google Gemini Schema");
      
      return null;
    }
  }
}