server:
  port : 3030

spring:
  config :
    mcp:
      server:
        url: http://localhost:8000/sse
  application:
    name : searcher
  ai:
      client:
        enabled : true
        name : searcher-mcp-client
        type : SYNC
        request-timeout : 60s
        sse :
          connections:
            server1:
              url : http://localhost:8000/sse
      auth:
        token : 461b9844ebe4805eef3fa62aa137397645a10ba209744de049bd91bf02b5f2c6
