server.port=3030

spring.application.name=searcher-app
spring.main.allow-bean-definition-overriding=true

# Google Gemini
spring.ai.google.genai.api-key=AIzaSyCDvDgQ_pjEH-9I0WQDAjrl8jvIxqW2I-Y

# MCP Client
spring.ai.mcp.client.enabled=true
spring.ai.mcp.client.initialized=false
spring.ai.mcp.client.name=searcher-mcp-client
spring.ai.mcp.client.type=SYNC
spring.ai.mcp.client.request-timeout=60s
spring.ai.mcp.client.sse.connections.server1.url=http://localhost:8000/sse

# Auth customizada (não é padrão do Spring AI)
spring.mcp.auth.token=461b9844ebe4805eef3fa62aa137397645a10ba209744de049bd91bf02b5f2c6
spring.mcp.server.url=http://localhost:8000/sse

# Neo4j graph
spring.neo4j.uri=bolt://localhost:9090
spring.neo4j.authentication.username=neo4j

# Neo4j vectorial
spring.neo4j.uri=neo4j://localhost:9090
spring.neo4j.ai.initialize-schema=true
spring.neo4j.ai.database-name=neo4j-vec
spring.neo4j.ai.embedding-dimension=1536
spring.neo4j.ai.distance-type=cosine