package com.agent.searcher.model.schema;

import java.util.List;
import java.util.Map;
import org.springframework.lang.Nullable;
import com.agent.searcher.rest.entity.ContentEntity;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.json.JsonMapper;
import com.google.genai.types.Content;

public record OutputSchema(
    @Nullable
    List<Message> messages,

    @Nullable
    @JsonProperty("retriveled_data")
    RetriveledData retriveledData,

    @Nullable
    @JsonProperty("searched_data")
    SearchedData searchedData
) {

  public record Message(
      String content
  ) {}

  public record RetriveledData(
      String id,
      String title,
      String content,
      @JsonProperty("saved_at")
      String savedAt,
      @JsonProperty("updateded_at")
      String updatedAt
  ) {
    public static RetriveledData fromEntity(ContentEntity entity) {
        return new RetriveledData(
        entity.getId(),
        entity.getTitle(),
        entity.getContent(),
        entity.getSavedAt(),
        entity.getUpdatedAt()
      );
    } 

}

  public record SearchedData(
      String title,
      String content
  ) {
    public static String toJSONSchema() {
      try {
        return new JsonMapper().writeValueAsString(
            (
            Map.of(
                  "type", "OBJECT",
                  "properties", Map.of(
                      "title",   Map.of("type", "STRING", "description", "Title of the search result"),
                      "content", Map.of("type", "STRING", "description", "Summary or body of the search result")
                  ),
                  "required", List.of("title", "content")
              )
        )
        );
      } catch (JsonProcessingException e) {
        System.err.print("Falha em serializar o schema SearchedData de saída do Google Gemini Schema");
        return null;
      }
    }
    
    public static ContentEntity toEntity(SearchedData data) {
      return new ContentEntity(
          data.title(),
          data.content()
      );
    }
  }

  public static String toJSONSchema() {
    JsonMapper mapper = new JsonMapper();
    try {
      return mapper.writeValueAsString(
        Map.of(
          "type", "OBJECT",
          "properties", Map.of(

              "messages", Map.of(
                  "type", "ARRAY",
                  "nullable", true,
                  "description", "List of messages generated by the agent",
                  "items", Map.of(
                      "type", "OBJECT",
                      "properties", Map.of(
                          "content", Map.of(
                              "type", "STRING",
                              "description", "The message content"
                          )
                      ),
                      "required", List.of("content")
                  )
              ),

              "retriveled_data", Map.of(
                  "type", "OBJECT",
                  "nullable", true,
                  "description", "Data retrieved from the local knowledge base",
                  "properties", Map.of(
                      "id",        Map.of("type", "STRING", "description", "Unique identifier"),
                      "title",     Map.of("type", "STRING", "description", "Title of the retrieved entry"),
                      "content",   Map.of("type", "STRING", "description", "Full content of the retrieved entry"),
                      "saved_at",   Map.of("type", "STRING", "description", "ISO-8601 creation timestamp"),
                      "updated_at", Map.of("type", "STRING", "description", "ISO-8601 last-update timestamp")
                  ),
                  "required", List.of("id", "title", "content", "saved_at", "updated_at")
              ),

              "searched_data", Map.of(
                  "type", "OBJECT",
                  "nullable", true,
                  "description", "Data obtained from an external web search",
                  "properties", Map.of(
                      "title",   Map.of("type", "STRING", "description", "Title of the search result"),
                      "content", Map.of("type", "STRING", "description", "Summary or body of the search result")
                  ),
                  "required", List.of("title", "content")
              )

          )
      )
      );
    } catch (JsonProcessingException e) {

      System.err.print("Falha em serializar o schema de saída do Google Gemini Schema");
      
      return null;
    }
  }
}